version: '3.8'
services:
  postgres-db:
    image: postgres:11
    ports:
      - "5434:5432"
    environment:
#      - SPRING_DATA_LIQUIBASE_CHANGE_LOG=classpath:db/changelog/db.changelog-master.xml
      - POSTGRES_DB=postgres
      - POSTGRES_USER=phoenix
      - POSTGRES_PASSWORD=software



  app:
    container_name: testApp
#    image: springbootapp:1.0
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./target/testProject-0.0.1-SNAPSHOT.jar:/opt/app/application.jar:ro
    depends_on:
      - postgres-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=phoenix
      - SPRING_DATASOURCE_PASSWORD=software
      - SPRING_DATA_LIQUIBASE_CHANGE_LOG=classpath:db/changelog/db.changelog-master.xml


